content:
  - label: "Els meus Pensaments"
    type: collection
    path: "src/content/blog"
    format: "json-frontmatter"
    extension: "md"
    fields:
      - name: "title"
        label: "Títol"
        type: "string"
      - name: "description"
        label: "Resum (Descripció)"
        type: "string"
      - name: "pubDate"
        label: "Data"
        type: "date"
        default: "now"
      - name: "heroImage"
        label: "Imatge (opcional)"
        type: "string"
        default: "/blog-placeholder-about.jpg"
      - name: "body"
        label: "Contingut del pensament"
        type: "rich-text"